- Routine-Machine/.gitignore
- Routine-Machine/lib/RingProgressBar.dart
- Routine-Machine/lib/main.dart
Created the Ring Progress Bar view. 
A few notes
* Did not manually change the font family because I figured we'll set that in a global theme
I added the component to the `main.dart` file so you can see what it looks like. 
I also copied the `.gitignore` file from the original flutter create app into the `Routine-Machine/` folder
resolves #4
> Create ring progress bar

- Server/.gitignore
- Server/README.md
- Server/jest.config.js
- Server/package-lock.json
- Server/package.json
- Server/src/app.ts
- Server/src/authenticate.ts
- Server/src/followRouter.ts
- Server/src/habitDataRouter.ts
- Server/src/server.ts
- Server/src/userRouter.ts
- Server/test/app.test.ts
- Server/tsconfig.json
- Express app with User, Follow, and HabitData Router Skeleton
- Implements Firebase authentication middleware
(This requires a project ID under which the user is authenticating from) 
- Sets up future tests with Jest
- Adds a quickstart README
> Setup the initial project structure

- Routine-Machine/lib/BottomNavBar.dart
- Routine-Machine/lib/main.dart
Fixes #9 
Created the bottom navigation bar for the app. Note the bar itself is one widget, but the floating button in the middle is part of the `Scaffold` widget provided by Flutter. So be sure to check both `BottomNavBar.dart` and `main.dart` to see what this looks like. 
The button icons on the navigation bar are currently clickable, but they don't do anything.
> Created Bottom Navigation Bar

- Routine-Machine/lib/Views/pages/FollowerPage.dart
- Routine-Machine/lib/Views/pages/FollowingPage.dart
- Routine-Machine/lib/Views/pages/FriendProfilePage.dart
- Routine-Machine/lib/Views/pages/HabitDetailPage.dart
- Routine-Machine/lib/Views/pages/HomePage.dart
- Routine-Machine/lib/Views/pages/LoginPage.dart
Added empty scaffold page widgets
> add empty scaffold for pages

- Routine-Machine/lib/Views/components/GreyContainer.dart
- Routine-Machine/lib/constants/Palette.dart
- Routine-Machine/lib/main.dart
Add most used colors for background, habit cards, and letters.
> Add most used colors in Palette

- Routine-Machine/lib/main.dart
#41 
lmao it doesn't change on my phone, but I copied the lines exactly the way it says to do it in the [docs](https://flutter.dev/docs/cookbook/design/fonts)
> Inject default font

- Routine-Machine/lib/Views/components/FollowRequestTile.dart
- Routine-Machine/lib/Views/pages/SearchResultPage.dart
- Routine-Machine/lib/Views/subviews/FollowRequestTileList.dart
Search Page now takes in the `UserProfile` data. 
Also now when the _Follow_ button is pressed, the button disappears and changes to the text `request sent`
> search page takes in UserProfile data

- Routine-Machine/lib/Views/components/RingProgressBar.dart
- Routine-Machine/lib/main.dart
Removed debug badge and added ring progress bar animation
> remove debug badge

- Routine-Machine/lib/Models/WidgetData.dart
- Routine-Machine/lib/Views/components/ProfileBarView.dart
- Routine-Machine/lib/Views/pages/AccountPage.dart
- Routine-Machine/lib/Views/pages/HomePage.dart
- Routine-Machine/lib/Views/pages/LoginPage.dart
Moved AccountPage to the 3rd tab along the bottom navigation bar. Can now also logout when you click _Logout_ on the AccountPage.
> Account page now in 3rd tab and can logout

- Routine-Machine/ios/Podfile
- Routine-Machine/ios/Podfile.lock
- Routine-Machine/ios/Runner.xcodeproj/project.pbxproj
- Routine-Machine/ios/Runner/Runner.entitlements
- Routine-Machine/lib/Views/components/SmallWidgetView.dart
- Routine-Machine/lib/Views/pages/FollowPage.dart
- Routine-Machine/lib/Views/pages/HabitDetailPage.dart
- Routine-Machine/lib/Views/pages/LoginPage.dart
- Routine-Machine/lib/api/authentication_provider.dart
- Routine-Machine/lib/main.dart
- Routine-Machine/pubspec.lock
- Routine-Machine/pubspec.yaml
Added Sign in with apple feature
> Sign in with Apple

- Routine-Machine/lib/Views/pages/LoginPage.dart
Fix firebase login stuck bug, added exception handler for the login button.
> Fix firebase login stuck bug

- Routine-Machine/lib/Views/components/CheckInItem.dart
- Routine-Machine/lib/Views/components/RingProgressBar.dart
- Routine-Machine/lib/Views/components/SmallWidgetView.dart
- Routine-Machine/lib/Views/components/TopBackBar.dart
- Routine-Machine/lib/Views/pages/AccountPage.dart
- Routine-Machine/lib/Views/pages/FollowPage.dart
- Routine-Machine/lib/Views/pages/FriendProfilePage.dart
- Routine-Machine/lib/Views/pages/HabitDetailPage.dart
- Routine-Machine/lib/Views/pages/MainDashboardPage.dart
- Routine-Machine/lib/Views/subviews/CheckInList.dart
- Routine-Machine/lib/Views/subviews/FollowerTileList.dart
- Routine-Machine/lib/Views/subviews/WidgetList.dart
- Routine-Machine/lib/constants/Constants.dart
**Bug fix**
1. Reverted widget detail page param settings.
**Improvements**
1. Modified Constants.dart file for Android devices to correctly utilize the SF Pro Rounded font
2. Added extra space between check-in items in the check-in list
3. Modified scaffold background color to white for all pages
4. Modified top back bar background color to white
5. Fixed a problem for small widget overflows on smaller devices
6. Added a temporary edit page in the Habit detail page
7. Added padding between elements in the Habit detail page
8. Fixed the inconsistent padding between widgets on the Main Dashboard Page
9. Fixed an issue of the following page where the top Following/Followers tab exceeds the safe area on iOS devices
10. Changed font size in small widgets
11. Changed font size in FollowPage …
> UI Fix + Optimization

- Routine-Machine/lib/Models/WidgetType.dart
- Routine-Machine/lib/Views/components/RingProgressBar.dart
- Routine-Machine/lib/Views/components/SmallWidgetView.dart
- Routine-Machine/lib/Views/components/WidgetTypeButton.dart
- Routine-Machine/lib/Views/pages/HabitDetailPage.dart
- Routine-Machine/lib/Views/subviews/WidgetColorPicker.dart
- Routine-Machine/lib/Views/subviews/WidgetTypePicker.dart
- Routine-Machine/lib/constants/Palette.dart
Have really tacky conversions for the habit color and the widget type because we don't use enumerated values for these (we use int and string respectively). We should probably enumerate these in our data model so we have better type checking and fewer edge cases to check.
> Implement edit habit detail page

- Routine-Machine/lib/Views/pages/AccountPage.dart
- Routine-Machine/lib/Views/pages/LoginPage.dart
- Routine-Machine/lib/Views/pages/ScanQRPage.dart
- Routine-Machine/lib/Views/pages/SetUserInfoPage.dart
- Routine-Machine/lib/main.dart
Upon sign up, user will be directed to this page. They can then enter the username, first name, and last name. Then it will go to the home page. Usernames are limited to [_$a-zA-Z] and first/last name are limited to only [a-zA-Z].
Also fixed sign up logic so emails can end with `.com`, `.net`, and `.edu` now. Before we only allowed `.com`
> Add page to add username, firstname, lastname

- Server/.gitignore
- Server/Procfile
- Server/package-lock.json
- Server/package.json
- Server/src/config/db-config.ts
- Server/src/config/env-config.ts
- Server/src/database.ts
New file added for deployment: Procfile
edit: 
env-config handles production and development environments differently 
note: 
the database still gets reset everytime the server restarts
resolves #3
> Deployment

- Routine-Machine/android/app/src/main/AndroidManifest.xml
- Routine-Machine/lib/Views/components/SmallWidgetView.dart
- Routine-Machine/lib/Views/pages/HomePage.dart
- Routine-Machine/lib/Views/pages/LoginPage.dart
- Routine-Machine/lib/Views/pages/MainDashboardPage.dart
- Routine-Machine/lib/Views/pages/SetUserInfoPage.dart
- Routine-Machine/lib/Views/subviews/WidgetList.dart
- Routine-Machine/lib/api/APIWrapper.dart
- Routine-Machine/lib/api/CSE.dart
connects apiwrapper to main dashboard
> Add habit api

- Routine-Machine/lib/Views/subviews/WidgetList.dart
An empty widget list (upon success of the api call) displays a default message saying to add habits with the + button
> Default message on empty list

- Routine-Machine/lib/Views/components/FollowRequestTile.dart
- Routine-Machine/lib/Views/components/FollowerRequestTile.dart
- Routine-Machine/lib/Views/pages/FollowPage.dart
- Routine-Machine/lib/Views/pages/FriendProfilePage.dart
- Routine-Machine/lib/Views/pages/SearchResultPage.dart
- Routine-Machine/lib/Views/subviews/friendWidgetList.dart
Got all follow page functions replaced with API Wrapper calls. There are still lots of bugs left, but wanna merge for now
* Accepting a follow request does NOT put the user in your followers list (think this is a bug in the backend?)
* because of this, can't implement the logic to see a followers' profile (aka can see if u are following them & can't see if u are not following them)
* Figure out how to see if you've already followed someone so that if you search them up again, you don't re-request to follow
* Add buttons to remove followers and unfollow people
> connect follow page and api

- Routine-Machine/lib/Views/pages/HabitDetailPage.dart
Overrode the android back button on the habit detail page. Pushing it will properly pass back the habit data.
> override android back button

- Server/src/query/user-query.ts
- Server/src/router/user-router.ts
- Server/src/service/user-service.ts
user's firstname and lastname update api endpoints created
> added set firstname and set lastname for users

- Server/src/router/user-router.ts
- Server/src/service/user-service.ts
user profile including firstname, lastname, username, public key, profile, and id can be fetched using user id. 
requires the user id to be equal to the token id
> added new api endpoint: get profile by Id

- Routine-Machine/lib/Views/pages/FriendProfilePage.dart
On the FriendProfilePage you can now follow/unfollow users and remove them from your follower list. 
If you pop back to the page with the follower/following list, the change might not show until you refresh the page. Didn't have time to implement a call to automatically refresh it.
> Add unfollow and remove follower buttons

- Server/src/app.ts
- Server/src/router/challenge.ts
- Server/src/service/user-service.ts
endpoint for validating private key 
requires that the user has been created already 
the GET reqeust to the endpoint /challenge will give you two strings: challengeString and encryptedString 
encyprtedString should be decrypted to match with the challenge String
> Validate private key backend

- Routine-Machine/lib/Views/pages/HomePage.dart
- Routine-Machine/lib/Views/pages/MainDashboardPage.dart
App will now update the list on close, when the app goes inactive in the background, and when it goes out of focus.
> update list on app close

- Routine-Machine/lib/Views/pages/LoginPage.dart
Fix the blank when using an existing account to sign up and add a sign up exception handler.
> Fix sign up error with existing account
